language: erlang

env:
  global:
    - PLATFORM=linux
    - LUAROCKS_VER=2.1.0
  matrix:
    # todo: install libffi and test ffi binding on Lua 5.1/5.2
    - LUA=lua5.1 ZMQ_VER=zeromq3 LZMQ=lzmq    PERF="NO" LUA_SFX=
    - LUA=lua5.1 ZMQ_VER=zeromq4 LZMQ=lzmq    PERF="NO" LUA_SFX=
    - LUA=lua5.2 ZMQ_VER=zeromq3 LZMQ=lzmq    PERF="NO" LUA_SFX=
    - LUA=luajit ZMQ_VER=zeromq3 LZMQ=lzmq    PERF="NO" LUA_SFX=jit
    - LUA=luajit ZMQ_VER=zeromq3 LZMQ=ffi     PERF="NO" LUA_SFX=jit
    - LUA=luajit ZMQ_VER=zeromq4 LZMQ=ffi     PERF="NO" LUA_SFX=jit
    - LUA=luajit ZMQ_VER=zeromq3 LZMQ=ffi-lua PERF="NO" LUA_SFX=jit
    # - LUA=lua5.1 ZMQ_VER=libzmq  LZMQ=lzmq    PERF="NO" LUA_SFX=
    # - LUA=luajit ZMQ_VER=libzmq  LZMQ=ffi-lua PERF="NO" LUA_SFX=jit

branches:
  only:
    - master

before_install:
  - bash .travis/setup_lua.sh
  - if [ "$ZMQ_VER" == "libzmq" ]; then
      bash .travis/setup_sodium.sh;
    fi
  - if [ "$ZMQ_VER" == "zeromq4" ]; then
      bash .travis/setup_sodium.sh;
    fi
  - bash .travis/setup_zmq.sh

install:
  - sudo luarocks install https://raw.github.com/moteus/lunit/moteus-skip/rockspecs/lunitx-scm.mot.skip-0.rockspec
  - sudo luarocks install https://raw.github.com/moteus/lua-llthreads2/master/rockspecs/lua-llthreads2-scm-0.rockspec
  - if [ $LZMQ = "ffi-lua" ]; then
      sudo luarocks install https://raw2.github.com/justincormack/ljsyscall/master/rockspec/ljsyscall-0.9-1.rockspec;
      sudo luarocks make rockspecs/lzmq-ffi-scm-0.rockspec;
    else
      sudo luarocks make rockspecs/lzmq-scm-0.rockspec;
    fi

script: 
  - cd test 
  - lunit.sh -i lua$LUA_SFX utest.lua
  - lunit.sh -i lua$LUA_SFX test_proxy.lua
  - lua$LUA_SFX test_threads.lua
  - lua$LUA_SFX test_threads_arg.lua
  - lua$LUA_SFX test_threads_fork_arg.lua
  - lua$LUA_SFX test_threads_fork.lua
  - lua$LUA_SFX test_threads_file.lua
  #- if [ "$ZMQ_VER" == "libzmq" ]; then
  #    lua$LUA_SFX test_req_relaxed.lua;
  #  fi
  - if [ $PERF = "YES" ]; then
      cd $TRAVIS_BUILD_DIR;
      mkdir ./examples/perf2/libzmq;
      sudo cp ./$ZMQ_VER/perf/inproc_lat ./examples/perf2/libzmq/;
      sudo cp ./$ZMQ_VER/perf/inproc_thr ./examples/perf2/libzmq/;
      cd ./examples/perf2;
      sudo luajit runner.lua;
    fi

notifications:
  email:
    on_success: change
    on_failure: always
